name: Create Archive

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        directory: 'cloud-functions/java'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}