name: Create GCP Cloud Functions releases

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Zip Java Cloud Functions
      uses: thedoctor0/zip-release@master
      with:
        filename: 'cloud-functions-java-release.zip'
        directory: 'cloud-functions/java'

    - name: Zip Python Cloud Functions
      uses: thedoctor0/zip-release@master
      with:
        filename: 'cloud-functions-python-release.zip'
        directory: 'cloud-functions/python'

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "GCP - Cloud Functions"
        files: |
          LICENSE.txt
          **/*.zip